### ISSUE TITLE
Add migrating from V4 guide

### ISSUE THREAD

**Issue by vikiival** [paraspell/xcm-tools#207]
### Context 

Seems that 53e81b56523e14e90f5f1ffc0103cb2bd9420c08 was a pretty big commit.
And it was a breaking change.

### Task

What I would expect is to have somewhere a migration guide from v4 to v5.

I imagine that as an example code snippets so apps can integrate that easily.

**Comment by dudo50** [comment]
There were no breaking changes, dApps can integrate the same as before (We would have notified them if there were breaking changes). There were key features added which is why we bumped to v5. Let us know if you would still like to get an update as to what was added.

With kind regards,
Team ParaSpell
